### ISSUE TITLE
File format and hardware requirements?

### ISSUE THREAD

**Issue by dwiest** [Chuny1/3DGPT#1]
The demonstration images/videos look great and I'm anxiously awaiting the code drop.  The summary of your paper mentions Blender integration; is the glTF format supported?  It would be very cool to use your tool to generate a Decentraland scene!

Do you have any information about hardware requirements for your code?  Is this something that could be run in a container on someone's workstation, or would I need to use something more capable like an EC2 G5 instance?

**Comment by 3481554467** [comment]
+1

**Comment by Chuny1** [comment]
> The demonstration images/videos look great and I'm anxiously awaiting the code drop. The summary of your paper mentions Blender integration; is the glTF format supported? It would be very cool to use your tool to generate a Decentraland scene!
> 
> Do you have any information about hardware requirements for your code? Is this something that could be run in a container on someone's workstation, or would I need to use something more capable like an EC2 G5 instance?

Thank you for your interest and attention to our project, and we appreciate your insightful question! : )

The generated result can be exported  as gITF files using blender directly. Hardware needs vary with scene complexity, especially mesh face count. Our project used InfiniGen, realistically rendering all geometries, including distant features, which increases complexity compared to similar scenes in games or VR.

Scene generation and rendering, as demonstrated in our paper and website, can be rapidly done with a single A100 GPU, though an RTX 3070 is also sufficient. For simpler assets like trees or flowers, a laptop such as a Mac Pro works well. For specific hardware requirements, see the InfiniGen(https://github.com/princeton-vl/infinigen) repository.

**Comment by GreatSarmad** [comment]
I used infinigen before it pretty awesome, and i have RTX3080, but i kept having issues with generation of certain objects, i kept getting random white cubes to swan, i haven tried it in a while maybe they fixed it. Still I hope you release your code soon, can't wait to try it, so I am no expert more like a hobby, so please make the set up really user friendly :) maybe even a clip on YT how to use it. Also so far i saw you make terrain and vegetation, any plans to add buildings or animals?
