### ISSUE TITLE
Can you release your code now?

### ISSUE THREAD

**Issue by 3481554467** [Chuny1/3DGPT#2]
It looks like a great job, wait and see

**Comment by Chuny1** [comment]
Thank you for your interest in our project! 🥰 We're currently enhancing the user interface and refining the InfiniGen code to provide greater control in 3D modeling. The complete code will be fully available after acceptance, but we're planning to release a few simple demos shortly. 🥳

We're eager to gather suggestions for these demos and will be focusing on this soon. Detailed plans for the repository's development will be outlined in the README shortly.

**Comment by 3481554467** [comment]
> Thank you for your interest in our project! 🥰 We're currently enhancing the user interface and refining the InfiniGen code to provide greater control in 3D modeling. The complete code will be fully available after acceptance, but we're planning to release a few simple demos shortly. 🥳
> 
> We're eager to gather suggestions for these demos and will be focusing on this soon. Detailed plans for the repository's development will be outlined in the README shortly.

Thanks for the reply! If possible, can you release the content about the LLM agent, such as general training methods ,how to get the agent’s training data ， share related literature?I`m very interested in this part. Thank you very much

**Comment by Chuny1** [comment]
> > Thank you for your interest in our project! 🥰 We're currently enhancing the user interface and refining the InfiniGen code to provide greater control in 3D modeling. The complete code will be fully available after acceptance, but we're planning to release a few simple demos shortly. 🥳
> > We're eager to gather suggestions for these demos and will be focusing on this soon. Detailed plans for the repository's development will be outlined in the README shortly.
> 
> Thanks for the reply! If possible, can you release the content about the LLM agent first? such as general training methods ,how to get the agent’s training data ， share related literature?I`m very interested in this part. Thank you very much

In this project, we haven't employed any training or fine-tuning techniques. Instead, we've utilized a technique known as prompting, well illustrated at https://huggingface.co/docs/transformers/main/tasks/prompting. The specific prompting texts used for each agent are detailed in our paper. Another crucial factor for the success of our method is the conversion of existing procedural generation code (InfiniGen) into a format that's more understandable for LLM agents, complete with thorough documentation. We plan to release this documentation soon.

**Comment by 3481554467** [comment]
> > > Thank you for your interest in our project! 🥰 We're currently enhancing the user interface and refining the InfiniGen code to provide greater control in 3D modeling. The complete code will be fully available after acceptance, but we're planning to release a few simple demos shortly. 🥳
> > > We're eager to gather suggestions for these demos and will be focusing on this soon. Detailed plans for the repository's development will be outlined in the README shortly.
> > 
> > 
> > Thanks for the reply! If possible, can you release the content about the LLM agent first? such as general training methods ,how to get the agent’s training data ， share related literature?I`m very interested in this part. Thank you very much
> 
> 在这个项目中，我们没有采用任何培训或微调技术。相反，我们利用了一种称为提示的技术，[在 https://huggingface.co/docs/transformers/main/tasks/prompting](https://huggingface.co/docs/transformers/main/tasks/prompting) 中得到了很好的说明。我们的论文详细介绍了用于每个代理的特定提示文本。我们方法成功的另一个关键因素是将现有的程序生成代码（InfiniGen）转换为LLM代理更容易理解的格式，并配有完整的文档。我们计划很快发布此文档。

Thanks for the reply, it helps a lot.

**Comment by OleLukCie** [comment]
**Amazing work!**
I saw it the day you first posted it on the site. After that, I read your article "**_3D-GPT: PROCEDURAL 3D MODELING WITH LARGE LANGUAGE MODELS_**". So far, I haven't seen your updates. Looking forward to hearing from you.
